// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARsoRxeawD1ZLURkgvcmaTn-YNg6x2WHc',
    appId: '1:77780705277:web:80ab71d44f9d19c6a48394',
    messagingSenderId: '77780705277',
    projectId: 'logreg-188ae',
    authDomain: 'logreg-188ae.firebaseapp.com',
    storageBucket: 'logreg-188ae.appspot.com',
    measurementId: 'G-NQFDK518DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5sK4oKeiMvdW4t67mxhJ4k6Kv0SNgTms',
    appId: '1:77780705277:android:d389b10fbce3bdc8a48394',
    messagingSenderId: '77780705277',
    projectId: 'logreg-188ae',
    storageBucket: 'logreg-188ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY6aQdRAEFCh8-aTdgDwoctMOuQntaVGw',
    appId: '1:77780705277:ios:3c1b39e5085d8f8ba48394',
    messagingSenderId: '77780705277',
    projectId: 'logreg-188ae',
    storageBucket: 'logreg-188ae.appspot.com',
    iosClientId: '77780705277-33i5n66jv82qg02rgc0k8a3s8u3f8emq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY6aQdRAEFCh8-aTdgDwoctMOuQntaVGw',
    appId: '1:77780705277:ios:3a61263e143fc044a48394',
    messagingSenderId: '77780705277',
    projectId: 'logreg-188ae',
    storageBucket: 'logreg-188ae.appspot.com',
    iosClientId: '77780705277-i3c6r4r9hfgj13n1o745855oa9bftit4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginRegister.RunnerTests',
  );
}
